![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [14]:
import numpy as np
my_array = np.arange(0,10)
print(my_array[10:0:-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [15]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [16]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [17]:
matriz4 = np.arange(1,21).reshape((4, 5))
print(matriz4)
matriz4 = np.flip(matriz4)
print("----")
print(matriz4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
----
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [18]:
# OTRO METODO
matriz4 = np.arange(1,21).reshape((4, 5))
print(matriz4[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [19]:
matriz4 = np.arange(1,21).reshape((4, 5))
splith_array4, resto2 = np.hsplit(matriz4, [2])
splitv_array4, resto2 = np.vsplit(splith_array4, [2])
print (splitv_array4)

[[1 2]
 [6 7]]


In [20]:
# ALTERNATIVA PROFE
matriz4 = np.arange(1,21).reshape((4, 5))
np.vsplit(np.hsplit(matriz4, [2])[0], [2])[0]

array([[1, 2],
       [6, 7]])

In [21]:
# CON SLICING
matriz4 = np.arange(1,21).reshape((4, 5))
print(matriz4[:2,:2])

[[1 2]
 [6 7]]


In [22]:
# CON MASCARAS
matriz4 = np.arange(1,21).reshape((4, 5))
mask = ([True,True,False, False])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [23]:
matriz4 = np.arange(1,21).reshape((4, 5))
print(matriz4)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [24]:
matriz4split = matriz4.copy()
matriz4split = matriz4[np.ix_([0,2], [0,2,4])]
print(matriz4split)

[[ 1  3  5]
 [11 13 15]]


In [25]:
# CORRECCION CON SLICING
print(matriz4[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [26]:
matriz4 = np.arange(1,21).reshape((4, 5))
print(matriz4)
matriz4 = np.flip(matriz4)
print(matriz4)
matriz4 = np.flip(matriz4, axis=0)
print(matriz4)
matriz4, resto = np.vsplit(matriz4, [3])
print(matriz4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


In [27]:
print(matriz4)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [28]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [29]:
x = x[x == "Loro"]
print(x)

['Loro' 'Loro']


In [30]:
x_bools = np.array(x == "Loro")
print(x[x_bools])

['Loro' 'Loro']


In [31]:
loros = np.array([animal for animal in x if animal == "Loro"])

print(loros)

['Loro' 'Loro']


In [32]:
x == x[np.where(x == "Loro")]
print(x)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [157]:
secuencia = np.arange(1,21)
print(secuencia)
secuencia = secuencia.reshape(2,5,2)
print(secuencia)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [36]:
tablero = np.full(10,"0")
print(tablero)
print(tablero.nbytes)
tablero[4] = 1
print(tablero)
tablero.nbytes

['0' '0' '0' '0' '0' '0' '0' '0' '0' '0']
40
['0' '0' '0' '0' '1' '0' '0' '0' '0' '0']


40

In [34]:
tablero2 = np.zeros(10)
print(tablero2)
print(tablero2.nbytes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [174]:
vector = np.arange(10,50)
vector = np.flip(vector)
print(vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [37]:
vector12 = np.array([1,2,0,0,4,0])
mascara = np.where(vector12 != 0)
print(mascara[0]) #Porque sin [0], nos devolvería una tupla con el array de las posiciones dentro


[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [41]:
matriz13 = (np.random.randint(100, size=(10,10)))
print(matriz13)
print (np.min(matriz13))
print(np.max(matriz13))

[[19 45 48  2 46 86 72 44 22 21]
 [ 7 99 92 68 85 15 29 13 88 62]
 [22 98 26 76  3 33 91 40 75 99]
 [63 74 77 53 73 35  3 84 57 25]
 [92 20 37 15 90 79 18 16 59 14]
 [86 15 32 75  2 72  1 60 24 31]
 [60 73 77 85 27 96 27 59 97 19]
 [56 97 63 10 65 56 38 48 59  4]
 [41 17 77 23 59 86  4 41 97 21]
 [10 45 91 31 40 82 23 67 57 32]]
1
99


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [43]:
vector14 = np.arange(30)
print (vector14)
print(np.median(vector14))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
14.5


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [230]:
array15 = np.ones((5,5))
array15[1:-1, 1:-1] = 0
print(array15)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [51]:
matriz16 = np.ones((8,8))
matriz16[::2,::2] = 0
matriz16[1::2,1::2] = 0
print(matriz16)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [52]:
array_a = np.array([0, 1])

In [53]:
array_b = np.array([1, 0])

In [54]:
tiles = np.stack((array_a,array_b))
tiles = np.tile(tiles, (4,4))
print(tiles)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [56]:
array18 = np.random.random((5,5))
print (array18)
resultado = (np.mean(array18))/(np.std(array18))
print(resultado)

[[0.10432919 0.30711029 0.17551545 0.34438919 0.08748902]
 [0.96903302 0.27078682 0.50657168 0.02180824 0.35194028]
 [0.76735936 0.34016215 0.05214103 0.30543767 0.54983609]
 [0.05295345 0.3362188  0.12330086 0.01017898 0.56892196]
 [0.55628529 0.63332979 0.73141041 0.11657982 0.19389036]]
1.3256556279655944


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [59]:
array19 = np.arange(11)
print(array19)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [60]:
array20  = np.where((array19 > 3) & (array19 < 8), -1, array19)
print(array20)

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


In [80]:
array19 [(array19 > 3) & (array19 <= 8)]  *= -1
print(array19)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]
